apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-service
  namespace: ai-crypto-browser
  labels:
    app.kubernetes.io/name: browser-service
    app.kubernetes.io/component: browser
    app.kubernetes.io/part-of: ai-crypto-browser
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: browser-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: browser-service
        app.kubernetes.io/component: browser
        app.kubernetes.io/part-of: ai-crypto-browser
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: browser-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: browser-service
        image: ai-crypto-browser/browser-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8082
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ai-crypto-browser-config
              key: BROWSER_SERVICE_PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ai-crypto-browser-config
              key: LOG_LEVEL
        - name: LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              name: ai-crypto-browser-config
              key: LOG_FORMAT
        - name: REDIS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_AUTH_TOKEN
        - name: REDIS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_ENDPOINT
        - name: OLLAMA_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-crypto-browser-config
              key: OLLAMA_HOST
        - name: OLLAMA_MODEL
          valueFrom:
            configMapKeyRef:
              name: ai-crypto-browser-config
              key: OLLAMA_MODEL
        envFrom:
        - configMapRef:
            name: ai-crypto-browser-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: browser-cache
          mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: browser-cache
        emptyDir:
          sizeLimit: 1Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: browser-service
  namespace: ai-crypto-browser
  labels:
    app.kubernetes.io/name: browser-service
    app.kubernetes.io/component: browser
    app.kubernetes.io/part-of: ai-crypto-browser
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: browser-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: browser-service
  namespace: ai-crypto-browser
  labels:
    app.kubernetes.io/name: browser-service
    app.kubernetes.io/component: browser
    app.kubernetes.io/part-of: ai-crypto-browser
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: browser-service
  namespace: ai-crypto-browser
  labels:
    app.kubernetes.io/name: browser-service
    app.kubernetes.io/component: browser
    app.kubernetes.io/part-of: ai-crypto-browser
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: browser-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
