apiVersion: v1
kind: Namespace
metadata:
  name: agentic-browser
  labels:
    name: agentic-browser
    environment: production
    app.kubernetes.io/name: agentic-browser
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: ai-agentic-browser
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "AI Agentic Browser application namespace"
    contact: "devops@ai-agentic-browser.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: agentic-browser
data:
  POSTGRES_DB: "agentic_browser"
  POSTGRES_USER: "postgres"
  REDIS_URL: "redis://redis-service:6379"
  DATABASE_URL: "postgres://postgres:password@postgres-service:5432/agentic_browser?sslmode=disable"
  CORS_ALLOWED_ORIGINS: "https://yourdomain.com,https://www.yourdomain.com"
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_WINDOW: "60"
  AI_MODEL: "gpt-4-turbo-preview"
  MAX_TOKENS: "2000"
  TEMPERATURE: "0.7"
  CHROME_HEADLESS: "true"
  CHROME_NO_SANDBOX: "true"
  MAX_CONCURRENT_SESSIONS: "10"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: agentic-browser
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your-secure-postgres-password"
  JWT_SECRET: "your-super-secure-jwt-secret"
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  ETHEREUM_RPC_URL: "your-ethereum-rpc-url"
  POLYGON_RPC_URL: "your-polygon-rpc-url"
  ARBITRUM_RPC_URL: "your-arbitrum-rpc-url"
  OPTIMISM_RPC_URL: "your-optimism-rpc-url"
  COINGECKO_API_KEY: "your-coingecko-api-key"
  ALCHEMY_API_KEY: "your-alchemy-api-key"
  WALLETCONNECT_PROJECT_ID: "your-walletconnect-project-id"
  GRAFANA_PASSWORD: "your-grafana-password"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: agentic-browser-quota
  namespace: agentic-browser
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: agentic-browser-limits
  namespace: agentic-browser
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
