apiVersion: v2
name: ai-agentic-browser
description: A Helm chart for AI Agentic Browser platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/ai-agentic-browser/ai-agentic-browser
sources:
  - https://github.com/ai-agentic-browser/ai-agentic-browser
maintainers:
  - name: AI Agentic Browser Team
    email: devops@ai-agentic-browser.com
keywords:
  - ai
  - automation
  - browser
  - web3
  - microservices
annotations:
  category: Application
  licenses: MIT
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nginx-ingress
    version: 4.x.x
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
  - name: jaeger
    version: 0.x.x
    repository: https://jaegertracing.github.io/helm-charts
    condition: tracing.jaeger.enabled
