# AI Agentic Browser Main Configuration

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576

# Database Configuration
database:
  host: "localhost"
  port: 5432
  name: "agentic_browser"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_connections: 100
  max_idle_connections: 10
  max_lifetime: "1h"
  log_level: "warn"

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10
  min_idle_connections: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  pool_timeout: "4s"
  idle_timeout: "5m"

# JWT Configuration
jwt:
  secret: "your-super-secret-jwt-key"
  expiry: "24h"
  refresh_expiry: "168h"
  issuer: "ai-agentic-browser"
  algorithm: "HS256"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  add_caller: true
  add_trace: true

# CORS Configuration
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  exposed_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 86400

# Rate Limiting Configuration
rate_limit:
  enabled: true
  requests_per_minute: 1000
  burst: 100
  skip_successful: false
  key_generator: "ip"

# Security Configuration
security:
  encryption_key: "your-32-character-encryption-key"
  csrf_secret: "your-csrf-secret-key"
  secure_cookies: false
  same_site_cookies: "lax"
  password_min_length: 8
  max_login_attempts: 5
  lockout_duration: "15m"

# File Upload Configuration
upload:
  max_file_size: "10MB"
  upload_path: "./uploads"
  allowed_types:
    - "jpg"
    - "jpeg"
    - "png"
    - "gif"
    - "pdf"
    - "doc"
    - "docx"

# Feature Flags
features:
  ai_agent: true
  browser_automation: true
  web3_integration: true
  multi_tenancy: false
  analytics: true
  notifications: true

# Environment Configuration
environment: "development"
debug: false
enable_pprof: false
pprof_port: 6060
