global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'ai-agent'
    static_configs:
      - targets: ['ai-agent:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'browser-service'
    static_configs:
      - targets: ['browser-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'web3-service'
    static_configs:
      - targets: ['web3-service:8084']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
