apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ai-crypto-browser-base

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- services/api-gateway.yaml
- services/auth-service.yaml
- services/browser-service.yaml
- services/web3-service.yaml
- services/frontend.yaml

commonLabels:
  app.kubernetes.io/name: ai-crypto-browser
  app.kubernetes.io/version: "1.0.0"

images:
- name: ai-crypto-browser/api-gateway
  newTag: latest
- name: ai-crypto-browser/auth-service
  newTag: latest
- name: ai-crypto-browser/browser-service
  newTag: latest
- name: ai-crypto-browser/web3-service
  newTag: latest
- name: ai-crypto-browser/frontend
  newTag: latest
