apiVersion: v1
kind: Namespace
metadata:
  name: ai-crypto-browser
  labels:
    name: ai-crypto-browser
    app.kubernetes.io/name: ai-crypto-browser
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-crypto-browser-system
  labels:
    name: ai-crypto-browser-system
    app.kubernetes.io/name: ai-crypto-browser
    app.kubernetes.io/component: system
