# External Secrets Operator configuration for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: ai-crypto-browser
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
---
# Database Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: ai-crypto-browser
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: ai-crypto-browser/rds/postgres/password
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: ai-crypto-browser/rds/postgres/password
      property: password
  - secretKey: DB_HOST
    remoteRef:
      key: ai-crypto-browser/rds/postgres/password
      property: host
---
# Redis Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: ai-crypto-browser
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
  - secretKey: REDIS_AUTH_TOKEN
    remoteRef:
      key: ai-crypto-browser/elasticache/redis/auth-token
      property: auth_token
  - secretKey: REDIS_ENDPOINT
    remoteRef:
      key: ai-crypto-browser/elasticache/redis/auth-token
      property: endpoint
---
# JWT Secret (manually created for now)
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ai-crypto-browser
  labels:
    app.kubernetes.io/name: ai-crypto-browser
    app.kubernetes.io/component: auth
type: Opaque
data:
  # Base64 encoded JWT secret key (change this in production)
  JWT_SECRET: YWktY3J5cHRvLWJyb3dzZXItand0LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=
  JWT_EXPIRY: MjRo # 24h
---
# API Keys Secret (manually created for now)
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
  namespace: ai-crypto-browser
  labels:
    app.kubernetes.io/name: ai-crypto-browser
    app.kubernetes.io/component: web3
type: Opaque
data:
  # Base64 encoded API keys (add your actual API keys)
  ETHEREUM_RPC_URL: aHR0cHM6Ly9tYWlubmV0LmluZnVyYS5pby92My9ZT1VSX0lORlVSQV9LRVk=
  POLYGON_RPC_URL: aHR0cHM6Ly9wb2x5Z29uLW1haW5uZXQuaW5mdXJhLmlvL3YzL1lPVVJfSU5GVVJBX0tFWQ==
  BSC_RPC_URL: aHR0cHM6Ly9ic2MtZGF0YXNlZWQuYmluYW5jZS5vcmcv
  COINGECKO_API_KEY: WU9VUl9DT0lOR0VDS09fQVBJX0tFWQ==
  COINMARKETCAP_API_KEY: WU9VUl9DT0lOTUFSS0VUQ0FQX0FQSV9LRVk=
