apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ai-crypto-browser-dev

namespace: ai-crypto-browser

resources:
- ../../base

commonLabels:
  environment: dev

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

configMapGenerator:
- name: ai-crypto-browser-config
  behavior: merge
  literals:
  - APP_ENV=development
  - LOG_LEVEL=debug
  - METRICS_ENABLED=true

images:
- name: ai-crypto-browser/api-gateway
  newTag: dev-latest
- name: ai-crypto-browser/auth-service
  newTag: dev-latest
- name: ai-crypto-browser/browser-service
  newTag: dev-latest
- name: ai-crypto-browser/web3-service
  newTag: dev-latest
- name: ai-crypto-browser/frontend
  newTag: dev-latest
